version: "2"
services:
  recognition-toolkit:
    image: quay.io/turner/recognition-toolkit:0.3.1
    ports:
    - 80:5050
    environment:
      PORT: 5050
      SEARCH_KEY: ${SEARCH_KEY}
      SEARCH_ID: ${SEARCH_ID}
      HEALTHCHECK: "/hc"

