version: "2"
services:
  object_detection:
    image: turnerlabs/recognition-toolkit:0.1.1
    ports:
    - 80:5050
    environment:
      PORT: 5050
      SEARCH_KEY: ${SEARCH_KEY}
      SEARCH_ID: ${SEARCH_ID}

